export const SET_FILTER = 'SET_FILTER';
export const SPOTIFY_REQUEST = 'SPOTIFY_REQUEST';
export const SPOTIFY_REQUEST_FAIL = 'SPOTIFY_REQUEST_FAIL';
export const SPOTIFY_REQUEST_SUCCESS = 'SPOTIFY_REQUEST_SUCCESS';
